HOTFIX: Fix Firebase import path in perplexityService.js
ERROR: Could not resolve '../firebase/firebase'
FIX: Changed to '../firebase/config' (correct path)

This was preventing deployment.